import "./globals.css";
import { Inter } from "next/font/google";
import TrpcProvider from "~/components/TrpcProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <ToastContainer />
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}

export default RootLayout;
