import "./globals.css";
import { Inter } from "next/font/google";
import { trpc } from "~/utils/trpc";
import TrpcProvider from "~/components/TrpcProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}

export default RootLayout;
